/* config.h.  Created from autogenerated config.h  */

#define PACKAGE "cscope"
#define VERSION "16.0a"

/* Found some version of curses that we're going to use */
#define HAS_CURSES 1

/* Use SystemV curses? */
#define USE_SYSV_CURSES 1

/* Define if you have the <dirent.h> header file, and it defines `DIR'. */
#define HAVE_DIRENT_H 1

/* Define if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define if you have the `fixkeypad' function. */
/* #undef HAVE_FIXKEYPAD */

/* Define if you have the `getcwd' function. */
#define HAVE_GETCWD 1

/* Define if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define if you have the `regex' library (-lregex). */
#define HAVE_LIBREGEX 1

/* Define if you have the `lstat' function. */
/* #undef HAVE_LSTAT */

/* Define if you have the `memcpy' function. */
#define HAVE_MEMCPY 1

/* Define if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define if you have the `memset' function. */
#define HAVE_MEMSET 1

/* Define if you have the <ndir.h> header file, and it defines `DIR'. */
/* #undef HAVE_NDIR_H */

/* Define if you have the `regcmp' function. */
/* #undef HAVE_REGCMP */

/* Define if you have the `regcomp' function. */
#define HAVE_REGCOMP 1

/* Define if you have the `setmode' function. */
#define HAVE_SETMODE 1

/* Define if you have the `snprintf' function. */
#define HAVE_SNPRINTF 1

/* Define if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define if you have the `strchr' function. */
#define HAVE_STRCHR 1

/* Define if you have the `strerror' function. */
#define HAVE_STRERROR 1

/* Define if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define if you have the <sys/dir.h> header file, and it defines `DIR'. */
/* #undef HAVE_SYS_DIR_H */

/* Define if you have the <sys/ndir.h> header file, and it defines `DIR'. */
/* #undef HAVE_SYS_NDIR_H */

/* Define if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define if you have the <sys/termios.h> header file. */
/* #undef HAVE_SYS_TERMIOS_H */

/* Define if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define if you have the <sys/window.h> header file. */
/* #undef HAVE_SYS_WINDOW_H */

/* Define if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define if you have the `vsnprintf' function. */
#define HAVE_VSNPRINTF 1

/* Define if you have the `_setmode' function. */
#define HAVE__SETMODE 1

/* Define as the return type of signal handlers (`int' or `void'). */
#define RETSIGTYPE void

/* Define if you have the ANSI C header files. */
#define STDC_HEADERS 1
